### ISSUE TITLE
Xenon Variable `regular` weight appears as `light` weight and vice versa in iTerm2

### ISSUE THREAD

**Issue by brendes** [githubnext/monaspace#1]
Steps to reproduce in iTerm2 (3.5.20231109-nightly):

1. Preferences -> Profiles -> select profile -> Text -> Font dropdown
2. Select "Monaspace Xenon Var"
3. Select weight "Regular"
4. Result: Font weight appears to be Light:
<img width="657" alt="image" src="https://github.com/githubnext/monaspace/assets/3211522/15e7d46c-c77e-4b25-a8a9-b230c110875a">

5. Select weight "Light"
6. Result: Font weight appears thicker than "Regular":
<img width="667" alt="image" src="https://github.com/githubnext/monaspace/assets/3211522/de49fee9-9808-4f8b-ae04-d831125a9dfb">

**Comment by rileycran** [comment]
This may be a result of lack of Variable Font support in iTerm2. Please try using the static .otf (rather than variable) fonts, and let me know if the issue persists. 

The family name will not have ‘var’ in it, for the static fonts, for instance.

**Comment by brendes** [comment]
OK, The regular OTFs do work as expected for me. I did not realize this was an issue with iTerm2, as variable Roboto Mono seems to work as expected, for example. Sorry about that, and thanks for the nice fonts.
