### ISSUE TITLE
Texture healing on `0` looks awkward

### ISSUE THREAD

**Issue by shanoaice** [githubnext/monaspace#109]
Texture healing is a great feautre, which makes most letter-only text looks much better, but its effect on numbers can be quite awkward, especially on number zero, for example: (Xenon Variant)
![image](https://github.com/githubnext/monaspace/assets/25174488/2b8077b4-8323-47a5-80f5-6c6d4b4f46f7)

Texture Healing makes the zero way too round, which looks quite unnatural in my humble opinion.

**Comment by Roshinator** [comment]
This also becomes an issue when working with numbers. For example this GUID has no consistency 
![image](https://github.com/githubnext/monaspace/assets/7969739/f70431f1-33d7-47d1-bfcb-cf9168143de7)

**Comment by yvvt0379** [comment]
Yeah, I think texture healing should not take effect on numbers. They should always be thebsame width.

**Comment by kenny-kvibe** [comment]
+1

**Comment by ToxicFrog** [comment]
See also #145 -- it's not just the width that's affected!

**Comment by Firestar-Reimu** [comment]
Maybe digits should not have texture healings.

**Comment by comiluv** [comment]
I noticed this a lot while coding some stuff in Neovim and had to turn off ligatures altogether

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
