### ISSUE TITLE
Ruby spaceship operator does not render correctly

### ISSUE THREAD

**Issue by jonmagic** [githubnext/monaspace#11]
:heart: this project so much, immediately switched to Monaspace Krypton 🤘 

I haven't figured out how to get `<=>` to look right. This is [used in Ruby](https://dev.to/jblengino510/the-spaceship-operator-in-ruby-2fmk) and [Python too](https://www.johndcook.com/blog/2021/04/12/spaceship-operator/).

<img width="40" alt="Untitled-2 — hamzo 2023-11-09 at 15 28 50" src="https://github.com/githubnext/monaspace/assets/623/6e7b9a29-4c2c-43c8-a736-cf4407623632">

**Comment by clementvtrd** [comment]
It is also used in PHP 😉

**Comment by edelkas** [comment]
Very useful ligature, apart from the spaceship operator in Ruby, Python or C++, this rendering issue happens with other similar symbols and operators, like in-place bitshifts (e.g. <<=) or Haskell, as mentioned in issues like #31 and #87, for instance.

**Comment by idan** [comment]
Fixed in ca8015b
