### ISSUE TITLE
Texture healing not consistent

### ISSUE THREAD

**Issue by nshern** [githubnext/monaspace#112]
Texture healing is not consistent. Three different widths of `m` next to an `i`

![Screenshot 2023-11-14 at 15 38 20](https://github.com/githubnext/monaspace/assets/90867839/0a8d1d65-e1d7-46f4-ba9e-26d9b4a6ef85)

Example is Monaspace Neon, using Helix editor in Wezterm.

**Comment by mcendu** [comment]
Example text:

    It mimics the appearance of chests to prey on unsuspecting adventurers.

I would say this is a fairly niche case, but some different handling in calt might be helpful here.

**Comment by dzolt** [comment]
@nshern How did you enabled texture healing in wezterm? I can't find the option

**Comment by valerykh** [comment]
> @nshern How did you enabled texture healing in wezterm? I can't find the option

According to WezTerm docs and VSCode instructions I came up with this to enable ligatures:
`config.harfbuzz_features = { "ss01", "ss02", "ss03", "ss04", "ss05", "ss06", "ss07", "ss08", "calt", "dlig" }`

On Monaspace website it' saying 

> calt (contextual alternates) activates ligatures that adjust the visual positioning of some character sequences without altering their shape or appearance. Activating this feature will also enable texture healing.

I'm not sure regarding texture healing but ligature works fine.
I hope this will useful.

**Comment by valerykh** [comment]
> Texture healing is not consistent. Three different widths of `m` next to an `i`
> 
> ![Screenshot 2023-11-14 at 15 38 20](https://private-user-images.githubusercontent.com/90867839/282811011-0a8d1d65-e1d7-46f4-ba9e-26d9b4a6ef85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTM5NzcsIm5iZiI6MTcxMzQ5MzY3NywicGF0aCI6Ii85MDg2NzgzOS8yODI4MTEwMTEtMGE4ZDFkNjUtZTFkNy00NmY0LWJhOWUtMjZkOWI0YTZlZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZWMxNWFiMGZhZTI2NDU4ZTNkMDAzMmM3NmY5Njg2NWU5MzQ5MDY0NGMxOTNiOTgxNjBjY2E4OGIyYzQ0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kkKjssPUsPlN0clWeS8vCQy3nKuGtDr5ptHEx-qNCrI)
> 
> Example is Monaspace Neon, using Helix editor in Wezterm.

Looks like it can be reproduced just in WezTerm. I can confirm the issue is the same in WezTerm and in Helix inside WezTerm
![CleanShot 2024-04-18 at 20 44 19@2x](https://github.com/githubnext/monaspace/assets/150704847/d3591a7b-c1b1-4545-bfb6-ed1d997d1072)

**Comment by heathercran** [comment]
This is a result of the texture healing feature. The first 'm' is the default width of the letter, the second one extends into the space of the 'i' preceding it, and the third one extends into the 'i's both before and after. So even though this is an odd-looking scenario, it is the intended effect of the feature. 

I do agree that the texture healing could be a little more distributed in this case, so I will look into what can be done with the OpenType code. In the meantime, if it's too distracting for you, you can turn off texture healing by disabling the `calt` feature.

**Comment by nshern** [comment]
> This is a result of the texture healing feature. The first 'm' is the default width of the letter, the second one extends into the space of the 'i' preceding it, and the third one extends into the 'i's both before and after. So even though this is an odd-looking scenario, it is the intended effect of the feature.
> 
> I do agree that the texture healing could be a little more distributed in this case, so I will look into what can be done with the OpenType code. In the meantime, if it's too distracting for you, you can turn off texture healing by disabling the `calt` feature.

Thanks for the repsonse. I guess this issue can be closed then as  I understand it to be working as intended. Jetbrains Mono it is!
