### ISSUE TITLE
Texture healing won't be disabled on VS Code

### ISSUE THREAD

**Issue by oissevalt** [githubnext/monaspace#118]
I saw in the guide that to disable texture healing and use only ligatures, what I need to do is omit `calt` in `editor.fontLigatures`. However, unless I set the value to `false`, texture healing will always be enabled regardless of the presence of `calt`.

<img width="540" alt="image" src="https://github.com/githubnext/monaspace/assets/57583509/d2bce61a-b93a-4a23-887d-9831a6ddd0d0">

Note the 0s with uneven widths.

Running VS Code 1.84.2 on macOS (arm64 23.1.0).

**Comment by nickmccurdy** [comment]
It seems to me like VSCode always enables `'calt'` and `'liga'` when passing a string, similarly to `true`:

> Enables/Disables font ligatures ('calt' and 'liga' font features). Change this to a string for fine-grained control of the 'font-feature-settings' CSS property.

Is this a bug in VSCode or a documentation inconsistency in Monaspace?

**Comment by oissevalt** [comment]
> It seems to me like VSCode always enables `'calt'` and `'liga'` when passing a string, similarly to `true`:

Yes as it seems. I entered an empty string and ligatures were still enabled. Also tested with Fira Code.

**Comment by nickmccurdy** [comment]
I'm assuming this is a bug in VSCode https://github.com/microsoft/vscode/issues/198517.

**Workaround:**: `"editor.fontLigatures": "'calt' off"`

**Comment by Krzysztof-Cieslak** [comment]
Closing as duplicate, in favour of #56
