### ISSUE TITLE
Asterisk ligatures introduce inconsistent formatting for glob paths 

### ISSUE THREAD

**Issue by kieran-ryan** [githubnext/monaspace#122]
The asterisk ligatures look great used in isolation, such as comments. However with file globs, they can introduce some variance, which across an extended list, might be more preferable with a consistent formatting - though there may be challenges to accommodate both.

- `/**/*`
- `*/**/*`
- `*/**/**`

<img width="110" alt="Screenshot 2023-11-16 at 00 21 24" src="https://github.com/githubnext/monaspace/assets/5904340/1e6017d0-cae9-46f9-b95e-2cfa73899414">

Though not an appropriate glob pattern, the following creates three different formattings outside the separators: single down; single up and single down; and double up.

<img width="116" alt="Screenshot 2023-11-16 at 00 31 40" src="https://github.com/githubnext/monaspace/assets/5904340/ebd03a12-2b6a-427e-bbdd-dd18297bc3d8">

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
