### ISSUE TITLE
make the underline apart as default and linked as ligature

### ISSUE THREAD

**Issue by Firestar-Reimu** [githubnext/monaspace#124]
In python, there are codes like `__init__(self)`

the 2 underlines will link together in monaspace, which is harder to read (as one will wonder if its 1 underline or 2 underlines)

I think we can make the underline apart as default (the width as like 80% width of x) and linked as ligature, like JetBrains Mono NL/JetBrains Mono, PT Mono and SF Mono also has the underline apart.

**Comment by Finii** [comment]
Just adding information to your Issue:
Hmm, looks like they are just as wide as the advance width, this is no liga at play (which I initially thought)

![image](https://github.com/githubnext/monaspace/assets/16012374/2f7d29a3-f900-413c-87cf-7a887909f76c)

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
