### ISSUE TITLE
Not intuitive three equals !== js ss01

### ISSUE THREAD

**Issue by reslear** [githubnext/monaspace#129]
two sticks is not intuitive and does not correspond to three equals.

<img width="609" alt="Screenshot 2023-11-17 at 02 32 19" src="https://github.com/githubnext/monaspace/assets/12596485/2741bcbd-bb85-4126-8590-d5342251f4f8">

<img width="301" alt="Screenshot 2023-11-17 at 02 35 46" src="https://github.com/githubnext/monaspace/assets/12596485/4f154be4-37a6-495b-b171-9e53daf75895">

**Comment by Pyrolistical** [comment]
How many stylistic sets can a font have? If it is unlimited, makes me wonder why we don't just have a javascript specific one, or heck we have computers that can produce language specific builds of each font variation. We wouldn't need to configure them

**Comment by movy** [comment]
Just stumbled upon  Monaspace's ligature for `!==` and I concur it's a bad choice, I had to retype it 3 times to figure that the difference between `!=` and `!==` as slightly elongated dashes, hard to notice when skimmin thru code and looks like a mistake most of the time. Please consider using Fira's triple-dash ligature for the strict inequality sign.

**Comment by Anoesj** [comment]
Fully agreed! Came here to look for or create this issue.

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
