### ISSUE TITLE
docs: `dlig` enables all ligatures

### ISSUE THREAD

**Issue by nickmccurdy** [githubnext/monaspace#131]
I've noticed that Monaspace enables all ligatures with `dlig`, so we can simplify the usage for VSCode:
```json
"editor.fontFamily": "'calt', 'liga', 'dlig'"
```
This is equivalent to enabling all ligatures separately:
```json
"editor.fontFamily": "'calt', 'liga', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06' 'ss07', 'ss08'"
```

**Comment by massimo-cassandro** [comment]
same for me
I noticed that there are differences between the https://monaspace.githubnext.com/ page and the repository readme

**Comment by nickmccurdy** [comment]
That's being tracked in #77. This issue is specifically about behavior in VSCode.

**Comment by quot** [comment]
This occurs in Wezterm too, so I don't think it's just a VSCode issue unless they both use Harfbuzz.

`dlig` seems to override and enable all `ss0x` options. Disabling a single `ss0x` option requires disabling `dlig`.

Disabling `dlig` doesn't seem to affect texture healing, so I don't mind that. But based on the Monaspace instructions, that doesn't seem to be how it's intended to work.

Wezterm font shaping docs: https://wezfurlong.org/wezterm/config/font-shaping.html

`dlig` disabled:
![image](https://github.com/githubnext/monaspace/assets/1102632/c61171a0-bf5d-433a-a9b2-d3dcaed5a456)

`dlig` enabled with no `ss0x` options:
![image](https://github.com/githubnext/monaspace/assets/1102632/d8eb4160-28be-427d-9aa7-643cce06bd98)

`dlig` enabled with `ss05` explicitly disabled:
![image](https://github.com/githubnext/monaspace/assets/1102632/e919d609-3365-44f8-84aa-eea527ffc4be)

`dlig` disabled with `ss05` explicitly disabled:
![image](https://github.com/githubnext/monaspace/assets/1102632/13b056b1-7d60-4c68-8d46-eebde5621426)

**Comment by nickmccurdy** [comment]
> This occurs in Wezterm too, so I don't think it's just a VSCode issue unless they both use Harfbuzz.

It's likely they both are, as Wezterm uses it by default and VSCode renders text with Chromium.

**Comment by Krzysztof-Cieslak** [comment]
`dlig` enabling everything is by-design behaviour (but it was introduced fairly late in the development cycle) - the problem is in the documentation/webpage which didn't get updated to cover this change.

Sorry for the confusion!

**Comment by nickmccurdy** [comment]
Thanks for clarifying, I had a feeling this would be the case but wanted to confirm.

**Comment by spikespaz** [comment]
This now does work:
![image](https://github.com/githubnext/monaspace/assets/12502988/9c486721-741d-4e1a-94cc-64b1d6369f5b)

**Comment by spikespaz** [comment]
This configuration does not work:
```json
{
  "[rust]": {
    "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss06', 'ss07', 'liga', 'calt'",
  },
}
```

Only when it is in the root `settings.nix` does the configuration above work.

**Comment by akhiljalagam** [comment]
@spikespaz can you post your config snippet please?

**Comment by spikespaz** [comment]
> @spikespaz can you post your config snippet please?

From where

**Comment by heathercran** [comment]
`dlig` is no longer used, as of version 1.1
