### ISSUE TITLE
Disable texture healing in linux

### ISSUE THREAD

**Issue by hiszd** [githubnext/monaspace#135]
I am looking to disable some of the features of this font for my terminal because of weird functionality with these features.
I notice in the docs there isn't really any explanation of how to do this with specific features of this font.
Maybe the docs aren't the place for this information, but it is unclear what OpenType feature to disable to disable these thing.

**Comment by Finii** [comment]
I believe you can disable whatever you want with https://github.com/MuTsunTsai/fontfreeze

**Comment by idan** [comment]
In 1.1, you can disable texture healing by turning off the `calt` OpenType setting.
