### ISSUE TITLE
Distribution on Homebrew?

### ISSUE THREAD

**Issue by rami3l** [githubnext/monaspace#14]
Thanks a lot for making this font, and I can't wait to try it out! 🎉

However, I believe you would make it even easier for macOS users to install (and upgrade) your font via a [`brew cask`](https://docs.brew.sh/Cask-Cookbook) instead of using a shell script. You can do this either by adding it to https://github.com/Homebrew/homebrew-cask-fonts, or by making a tap of your own including that cask. 🙇

**Comment by rami3l** [comment]
Closing with https://github.com/Homebrew/homebrew-cask-fonts/pull/8651.

**Comment by krehel** [comment]
Didn't realize there was an issue here when I authored the PR in Homebrew for this! I wasn't checking for issues on your side or I'd have linked; tried to get it in to Homebrew as quickly as possible! 😅

**Comment by idan** [comment]
Zomg, what did we do to deserve you all! 🥰 Thank you, thank you!
