### ISSUE TITLE
Digit 0 height doesn't match other digits in some applications

### ISSUE THREAD

**Issue by Reedbeta** [githubnext/monaspace#145]
Unsure if this is a font issue or a renderer issue, or an intersection of both, but I thought I'd start here.

Example string: `[Version 10.0.19045.3693]`

Here's how it renders in Windows Terminal, with Monaspace Neon:
![Windows Terminal](https://github.com/githubnext/monaspace/assets/1578730/952a847d-20d4-4850-b746-853ef0d16f6d)

The 0 in `19045` is visibly shorter than other digits. But the 0's in `10.0` appear to be the right height.

Looks similar in VSCode:
![VSCode](https://github.com/githubnext/monaspace/assets/1578730/ba09b6bc-1ebe-444c-95f5-1d1e9c146b2f)

Looks more correct in Visual Studio 2022:
![Visual Studio 2022](https://github.com/githubnext/monaspace/assets/1578730/8db424ae-204b-4030-8817-a94df86d9a02)

Looks good in Firefox as well:
![Firefox](https://github.com/githubnext/monaspace/assets/1578730/606f54bf-bd61-4e25-a232-8264919895a9)

**Comment by Firestar-Reimu** [comment]
Why the 0's in 10.0 is much wider than other digits? Is it a ligature like `0.0 -> eyes`?

**Comment by alexeyten** [comment]
@Firestar-Reimu that's “Texture Healing” https://monaspace.githubnext.com/

**Comment by Reedbeta** [comment]
Aesthetically, I don't love the wide zeroes - they look incongruous next to the other digits for me - but that's another issue. 🙂

**Comment by ToxicFrog** [comment]
I just came here to report an issue that I think might be the same thing. This is in VScode with ligatures enabled:

![image](https://github.com/githubnext/monaspace/assets/90456/e122fd0f-6927-4c42-b032-7867362c02ff)

And disabled:

![image](https://github.com/githubnext/monaspace/assets/90456/af3a10f8-700f-4837-b835-da0855f25185)

In both cases we get a lot of unusually short zeroes, but if ligatures are enabled the 0 following the leading 1, and only that 0, is the correct height. This is in vscode and you get the same effect with *any* non-false setting of `fontLigatures`, including ones that should be turning off texture healing.

**Comment by ToxicFrog** [comment]
On further reading, the "any non-false setting" is #118 which is a vscode bug, so this is in fact a texture healing bug with monaspace. `'calt' off` gives short zeroes everywhere, `'calt'` gives a mix of short and normal zeroes.

**Comment by Finii** [comment]
It would be interesting to know if you use the static or the variable font version?

**Comment by Finii** [comment]
The different zeros do have different heights, just by one unit, but nevertheless, that rounds either up or down when "hinting".

In this regard it would be also interesting if the behaviour you encounter changes if you change the font size by 1 or 2 pt. Or maybe look at ridiculously big letters like 60 pt, is the difference still one pixel?

![Screenshot 2023-12-19 at 20 13 45](https://github.com/githubnext/monaspace/assets/16012374/25ced84e-a20f-46de-9b4f-7e4dbdc6a308)

_Ignore the different position, the XY display on the bottom of the glyhs shows the green point at 1484 and 1485_

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
