### ISSUE TITLE
React fragment tags look unbalanced

### ISSUE THREAD

**Issue by Peeja** [githubnext/monaspace#147]
The closing tag for a React fragment is a ligature, but the opening one isn't, and the result comes out unbalanced:

![CleanShot 2023-11-21 at 15 51 45](https://github.com/githubnext/monaspace/assets/2407/6b35f0ec-272a-4938-aa32-6bbfdf3fea6a)

I think the closing tag ligature looks great, it would just look better if the opening tag matched it.

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
