### ISSUE TITLE
Incorrect macOS installation instructions

### ISSUE THREAD

**Issue by dbarros** [githubnext/monaspace#149]
The bash snippet shown to install the fonts in macOS are incorrect:

```
$ cd util
$ bash ./install_macos.sh
```

It results in the errors:

```
cp: ./fonts/otf/*: No such file or directory
cp: ./fonts/variable/*: No such file or directory
```

The `cd util` is not required. To install it should just say:

```
bash util/install_macos.sh
```

And a minor one: it's "macOS" not "MacOS"

**Comment by idan** [comment]
Fixed in 702a2568628b16fa3ddef4aae46e3e3e8c6b052a, 52cc7507c7f4b600925dc9f6c5e2dd1cfb575e11, 8847e6c809aae8afac2ea9e137850fe870862421
