### ISSUE TITLE
Can't see monaspace on terminal

### ISSUE THREAD

**Issue by episodman** [githubnext/monaspace#15]
I use gnome terminal and kitty.
I am not able to find monaspace font on kitty and gnome terminal..

**Comment by PThorpe92** [comment]
I can actually confirm it doesn't seem to be working on Kitty, ran `fc-cache` as well as `fc-list` to double check they were installed.

Works fine on alacritty though, awesome fonts!

**Comment by mjm** [comment]
Seems like something is off with the spacing. kitty is really picky about all of the characters being the same size. I tried doing [the fix described here](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font) to force the spacing to be 100 on the Xenon variant, and that got kitty to be able to use it, but it didn't look right. The cursor was positioned low relative to the text, and it didn't seem like all the characters had a consistent baseline.

**Comment by petejohanson** [comment]
You can use dconf-editor to force GNOME Terminal font setting and it looks great there. Annoying it filters from the list though in the UI.


https://fosstodon.org/@petejohanson/111384211402484279

**Comment by Finii** [comment]
Maybe Panose which is missing. See also #17

**Comment by egmontkob** [comment]
GNOME Terminal's Preferences dialog offers to choose from the fonts where `pango_font_family_is_monospace()` returns `true`.

I believe this method looks at a certain flag defined within font files, rather than actually measuring its glyphs, but I'm not familiar with the details here.

**Comment by Finii** [comment]
Could not find out what pango looks for, but usually that is Panose...

```python
def force_panose_monospaced(font):
    """ Forces the Panose flag to monospaced if they are unset or halfway ok already """
    # For some Windows applications (e.g. 'cmd'), they seem to honour the Panose table
    # https://forum.high-logic.com/postedfiles/Panose.pdf
    panose = list(font.os2_panose)
    if panose[0] == 0: # 0 (1st value) = family kind; 0 = any (default)
        panose[0] = 2 # make kind latin text and display
        logger.info("Setting Panose 'Family Kind' to 'Latin Text and Display' (was 'Any')")
        font.os2_panose = tuple(panose)
    if panose[0] == 2 and panose[3] != 9:
        logger.info("Setting Panose 'Proportion' to 'Monospaced' (was '%s')", panose_proportion_to_text(panose[3]))
        panose[3] = 9 # 3 (4th value) = proportion; 9 = monospaced
        font.os2_panose = tuple(panose)
```

[1] https://forum.high-logic.com/postedfiles/Panose.pdf

**Comment by marcaurele** [comment]
Kitty, Gnome terminal are running their own checks to see if the font is really a monospaced one or not. It's about this issue on the spacing, running `fc-list :spacing=100` does not list any of the Monaspace fonts in the list, but all the ones available for the gnome terminal for example.

**Comment by ToxicFrog** [comment]
This also affects Konsole, although in that case you can override it by ticking `show all fonts`. (It still doesn't *work properly* on Konsole, but doing this at least lets you select it.)

**Comment by alexeyten** [comment]
fonts-conf doesn't think that theese fonts are monospace. So one could force it with this little config:
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="scan">
        <test name="family" compare="contains">
            <string>Monaspace</string>
        </test>
        <edit name="spacing">
            <const>dual</const>
        </edit>
    </match>
</fontconfig>
```

Put it in `~/.config/fontconfig/conf.d/20-monaspace.conf` and run `fc-cache -f`.

**Comment by idan** [comment]
Whoops, GH auto closed this when I merged #125 

We'll produce a new build soon and check that this (and related issues) are solved.

**Comment by kwmlodozeniec** [comment]
Any idea when a new build will be produced?

**Comment by kwmlodozeniec** [comment]
Would it be possible to document the built process so it could be done by the community?

**Comment by xf0e** [comment]
> Whoops, GH auto closed this when I merged #125
> 
> We'll produce a new build soon and check that this (and related issues) are solved.

Any idei when a new build wlll be produced? Or did i miss, the build insctructions to build it by myself?

**Comment by Finii** [comment]
> Or did i miss, the build insctructions to build it by myself?

Well, I guess there are no build instructions needed, just open the `.glyphs` file(s) and `File` -> `Export...`

But there is no commit with anything new here, or did I miss that? In a branch maybe?

<img width="1582" alt="Screenshot 2024-03-25 at 13 24 15" src="https://github.com/githubnext/monaspace/assets/16012374/4e07d2e8-de75-4b15-8e80-0b305220d510">

**Comment by kwmlodozeniec** [comment]
@Finii a number of tweaks went in since the release that is currently available.

**Comment by Finii** [comment]
Oh, You are right :-D

![image](https://github.com/githubnext/monaspace/assets/16012374/7789814b-fe01-41c0-b471-637271e417b8)

**Comment by kwmlodozeniec** [comment]
the panos plags were set and that solves at least some issues raised all over the place 
![image](https://github.com/githubnext/monaspace/assets/1453791/946f62bf-187b-4f3e-a099-3f2c6bd51cb3)

**Comment by Finii** [comment]
Oh my... thats why I can not see my own commit :woman_facepalming: 

![image](https://github.com/githubnext/monaspace/assets/16012374/b4b8e261-36de-475f-90eb-85f0e2bceec4)

Usually my fork is called `fork` and upstream is `origin`, maybe I had no time back then ;)

**Comment by Finii** [comment]
I could upload the fixed files in a branch of my fork, if that helps.
Well, in fact that would not be allowed due to the RFN, strictly speaking. :grimacing:

**Comment by Finii** [comment]
Btw, I do not know if Panose is sufficient, another far more severe issue is
* #132

Unfortunately that is far from easily-fixable but a conceptual problem :unamused:

**Comment by kwmlodozeniec** [comment]
indeed, it would be great if the owners could do this or at least hand over to the community but there might be reasons beyond my understanding that could be preventing that.

**Comment by heathercran** [comment]
Fixed in version 1.1

**Comment by ToxicFrog** [comment]
> Oh, You are right :-D
> 
> ![image](https://private-user-images.githubusercontent.com/16012374/316518301-7789814b-fe01-41c0-b471-637271e417b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDcyNTgsIm5iZiI6MTcyMDY0Njk1OCwicGF0aCI6Ii8xNjAxMjM3NC8zMTY1MTgzMDEtNzc4OTgxNGItZmUwMS00MWMwLWI0NzEtNjM3MjcxZTQxN2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDIxMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmUyZjY3ZmExZjIxNjFlN2IxZjQxNzQ5ZjZiOWJmMDQ1MzdmZmFhNmRkZjMxODQ5ZGNkMDExNTdlMmVhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hmrhosxt8ZUCo0jbeAh2M0kClManzvTNAvcKmyUOtz0)
> 
What's this a screenshot from? I find it a lot more readable than the default `git log --graph`.

**Comment by Finii** [comment]
> What's this a screenshot from? I find it a lot more readable than the default `git log --graph`.

That's `tig` (`git` spelled backwards) https://jonas.github.io/tig/doc/tig.1.html

> Tig is an ncurses-based text-mode interface for git. It functions mainly as a Git repository browser, but can also assist in staging changes for commit at chunk level and act as a pager for output from various Git commands.

I usually do not like tools that do git commands for me (like lazygit), but I do use `tig` as `git log` / `git show` substitude and `tig blame` where you can easily jump the commits up and down.

All Linux distributions as well as Homebrew has packages.

To only other git tool I use is `fugitive` the vim plugin (in neovim). I rather like to interact with git directly.
