### ISSUE TITLE
Cannot choose Monaspace Neon in VSCode

### ISSUE THREAD

**Issue by trag1c** [githubnext/monaspace#154]
All of the following work fine:
```json
"editor.fontFamily": "'Monaspace Argon', monospace",
"editor.fontFamily": "'Monaspace Krypton', monospace",
"editor.fontFamily": "'Monaspace Xenon', monospace",
"editor.fontFamily": "'Monaspace Radon', monospace",
```
However, trying to set `'Monaspace Neon'` fails and VSCode just falls back to the default font.

Happens to me on macOS both when installing using the zip and through homebrew.

Note: `'Monaspace Neon Var'` works, but the weights behave weird so it's either too thin or too thick :/

**Comment by notken12** [comment]
I also have the same issue with VSCode

**Comment by idan** [comment]
Hi there,

It sounds like maybe something is wonky with Homebrew and/or caching.

We've seen lots of screenshots of people using Neon in VS Code, and we use it ourselves.

Font caching is super tricky to debug, maybe try fully uninstalling the fonts (homebrew and local files), reboot your machine, install just the files from the repo, and test again?

**Comment by notken12** [comment]
Uninstalling, rebooting and reinstalling worked for me, thanks.

**Comment by trag1c** [comment]
> Hi there,
> 
> It sounds like maybe something is wonky with Homebrew and/or caching.
> 
> We've seen lots of screenshots of people using Neon in VS Code, and we use it ourselves.
> 
> Font caching is super tricky to debug, maybe try fully uninstalling the fonts (homebrew and local files), reboot your machine, install just the files from the repo, and test again?

That fixed it for me, thanks :)

**Comment by notken12** [comment]
Hmm, it's broken for me again on my PC, but works on my laptop. I tried clearing VS Code's cache files from AppData/Roaming and it hasn't helped.
