### ISSUE TITLE
Missing <=> (spaceship) ligature for c++20

### ISSUE THREAD

**Issue by SavenkovIgor** [githubnext/monaspace#155]
This is a new c++ operator from c++20 standard

Expected behavior: This 3 symbols <=> has its own ligature.

Actual behavior: Applied ligature for 'less or equal' and then symbol 'more'

**Comment by biggianteye** [comment]
See #11

**Comment by christophberger** [comment]
Thanks @biggianteye. I did not search for "spaceship" in the issues, didn't even know that this operator has a name :)

**Comment by SavenkovIgor** [comment]
Closing due to dublicate
