### ISSUE TITLE
Add ligatures for <<, >>, <<=, and >>=

### ISSUE THREAD

**Issue by wpkelso** [githubnext/monaspace#161]
Currently, there are no ligatures included for the `<<`, `>>`, `<<=`, `>>=` operators. This becomes a particular problem in C/C++, where when all ligatures are enabled, the `<<=` and `>>=` operators become `<`+`<=` and `>`+`>=` where the second character in each operator is the `geq` or `leq` ligatures.

**Comment by dvdvgt** [comment]
Additionally, a ligature for `<=>` would also be nice.

**Comment by biggianteye** [comment]
> Additionally, a ligature for `<=>` would also be nice.

Already covered by #11

**Comment by coder0107git** [comment]
Part of this is already mentioned [here](https://github.com/githubnext/monaspace/issues/31).

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
