### ISSUE TITLE
Add ligature for ::*

### ISSUE THREAD

**Issue by dstoza** [githubnext/monaspace#163]
It would be nice to have a ligature version of `::*` where the asterisk is aligned vertically with the colons for use with wildcard imports in Rust.

**Comment by halaomer236** [comment]
السلام عليكم انا عمر

**Comment by halaomer236** [comment]
السلام عليكم انا عمر

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
