### ISSUE TITLE
Left shift and right shift assignment operators rendered wrong

### ISSUE THREAD

**Issue by LeoVasanko** [githubnext/monaspace#166]
A fairly common operator `<<=` in C and other languages is misrendered as `<` followed by `≤` (when ss2 or dlig is enabled). Similarly, right shift assignement `>>=` is misrendered as `>` and `≥`.

There should be ligatures to handle the shift assignment operators `<<=` and `>>=` with higher precedence than the `<=` or `>=` part of it as comparison.

**Comment by LeoVasanko** [comment]
There are also bit rotation operators `<<<=` and `>>>=` that while not part of standard C syntax are less used, but probably should not be too badly mishandled in font rendering either.

**Comment by Finii** [comment]
Related (partly duplicate)

* #161 

Maybe add the `<<<=` operators there as comment ;-)

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
