### ISSUE TITLE
equal character ligature displays weirdly

### ISSUE THREAD

**Issue by cxOrz** [githubnext/monaspace#168]
Monospace Argon:
![image](https://github.com/githubnext/monaspace/assets/32982052/29232d5e-6c30-4ab3-ab53-740ac1fbf8c4)

Fira Code:
![image](https://github.com/githubnext/monaspace/assets/32982052/37efada3-0ecb-430d-a56f-c27b50bec26b)

The FiraCode equal characters' behavior looks better.

**Comment by cyreb7** [comment]
I just ran into the same issue where my test output uses `================` as a line separator. 

Another example of how Jetbrains Mono handles the situation:

Jetbrains Mono:
![Screenshot from 2023-12-11 13-56-03](https://github.com/githubnext/monaspace/assets/1165781/e04ca6e6-b32e-4e02-bbd3-c5387886bcf6)

Monospace Argon
![Screenshot from 2023-12-11 13-55-50](https://github.com/githubnext/monaspace/assets/1165781/caa44ca6-ddf4-4395-9dcc-44bf9c16aa1e)

**Comment by viktor-yakubiv** [comment]
More than 3 equal signs appear in [setext heading notation](https://github.github.com/gfm/#setext-headings) in Markdown (CommonMark, GitHub Flaboured Markdown). I would love if Fira Code's behaviour is adopted here, it would make Markdown look nicer.

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
