### ISSUE TITLE
Fonts not selectable in gvim/gtk+

### ISSUE THREAD

**Issue by fefe17** [githubnext/monaspace#17]
gvim under Linux only lets you select fonts that have the monospace flag set in the truetype header.
These fonts don't. So I can't select them in my editor of choice.

Please set the monospace flag in the header!

**Comment by Finii** [comment]
Panose is (also?) not set, which some applications need.

![image](https://github.com/githubnext/monaspace/assets/16012374/4ee4547f-9a60-4b80-974b-f8c080d269e0)

**Comment by idan** [comment]
Whoops, GH auto closed this when I merged #125 

We'll produce a new build soon and check that this (and related issues) are solved.

**Comment by mscheper** [comment]
@fefe17: Many thanks for finding out why we can't see Monaspace in gvim; I've been poking at things for half an hour now. ☺ Do you know of a workaround?

**Comment by heathercran** [comment]
Fixed in version 1.1
