### ISSUE TITLE
Semiserious: Mona is a bad word

### ISSUE THREAD

**Issue by rjalexa** [githubnext/monaspace#173]
Just so that you know, but in Venice and surrounding areas Mona means Vagina and when applied to a person "Ti xe un mona" it means Idiot.

https://it.wiktionary.org/wiki/m%C3%B3na

So know that Vaginaspace will probably be very popular in those areas.

**Comment by alexeyten** [comment]
What about [Mona Lisa](https://en.wikipedia.org/wiki/Mona_Lisa)? :exploding_head:

**Comment by rjalexa** [comment]
Please note that Monna is with two Ns and is the abbreviation of Madonna, a kind title for ladies in the past. Mona is Vagina.

**Comment by comiluv** [comment]
I'm surprised that this issue has led me to yet another discovery that was unknown to me.
Mona.
How interesting.

**Comment by rjalexa** [comment]
Glad to contribute to international culture :)

**Comment by yvvt0379** [comment]
A selfish & childish person making trouble without a reason

**Comment by mrclayman** [comment]
There is always something in some language. I'm not sure if this issue was intended to be a tongue-in-cheek, but it's a tempest in a teacup kind of thing IMO.

**Comment by yvvt0379** [comment]
There's a village called Fucking in Austria. It means Focko's People. If the name of this village should be changed just because it's a bad word in English, don't you feel it's absurd?

**Comment by Krzysztof-Cieslak** [comment]
OK, discussion here is getting way too serious for something with "semiserious" in title ;-) 

As you may have guessed we're not planning to change the name of the fonts (`Mona The Octocat` has been part of GH brand for years - https://github.blog/2021-02-04-how-we-illustrate-at-github/).

But thanks for good laugh!
