### ISSUE TITLE
Overlapping characters following double ampersand (&&)

### ISSUE THREAD

**Issue by parkerbxyz** [githubnext/monaspace#190]
The following input... 

```shell
❯ echo "Hello, world!" && clear 
```

...produces the following:

<img src="https://github.com/githubnext/monaspace/assets/17183625/87bcd99e-77e8-419d-81e6-808c6982bc49" width="800px"> 

If I omit the space between `&&` and `clear`, the `&` and `c` characters overlap:

<img src="https://github.com/githubnext/monaspace/assets/17183625/25b9bc7f-ec9d-48f7-8d57-3df40f7cbe98" width="800px">

**Comment by kenmcd** [comment]
The && discretionary ligature (`dlig`) is two characters wide (AW 2480)
and the application is treating it as one character wide (AW 1240).

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
