### ISSUE TITLE
Arabic? 

### ISSUE THREAD

**Issue by Assurokilwr** [githubnext/monaspace#199]

**Comment by idan** [comment]
Sorry, we don't have any plans to implement Arabic at this time! Each character set is a huge undertaking (×5 fonts, plus texture healing, etc.) While I'd love to support every language under the sun, I don't think it's likely to happen anytime soon.

**Comment by t4rik** [comment]
> No description provided.

[Cascadia Code](https://github.com/microsoft/cascadia-code) support Arabic.
