### ISSUE TITLE
Add ligature for `/**`

### ISSUE THREAD

**Issue by marvinruder** [githubnext/monaspace#2]
Monaspace offers a ligature for the character sequence `/*`, which looks good on its own, but when typing `/**` to start e.g. a Javadoc or JSDoc comment, only the first two characters get replaced by the ligature, the last asterisk remains unchanged and is now on a different height than the first one:

<img width="86" alt="image" src="https://github.com/githubnext/monaspace/assets/18495294/2693e1f8-4857-45f4-bb77-f7248a37c64a">

This does not look too aesthetically pleasing. Any chance we might find a ligature for the entire `/**` in a future version of Monaspace?

**Comment by Ayesh** [comment]
They are used quite extensively in the PHP world as well.

**Comment by iwangbowen** [comment]
I encountered the same problem and had to remove `dlig` to make it look better

**Comment by techieshark** [comment]
I had to remove `dlig` and `ss07` to make it look better

**Comment by pvanb** [comment]
Maybe this belongs in a separate issue, but the sequence `**/` also comes up and would benefit from its own ligature as well:

![Screenshot 2023-11-13 at 12 16 30 PM](https://github.com/githubnext/monaspace/assets/823278/6165a736-96a8-4ddf-9ae8-0de525f060d6)

**Comment by kieran-ryan** [comment]
> Maybe this belongs in a separate issue, but the sequence `**/` also comes up and would benefit from its own ligature as well:

@pvanb, I have captured this as a separate issue (#122) as there appear to be a few unusual patterns that occur when using globs.

**Comment by idan** [comment]
Fixed in ca8015b
