### ISSUE TITLE
Packaging without .git history

### ISSUE THREAD

**Issue by simonsan** [githubnext/monaspace#204]
There is a [monaspace.zip](https://github.com/githubnext/monaspace/releases/download/v1.100/monaspace-v1.100.zip) attached to the [release](https://github.com/githubnext/monaspace/releases/tag/v1.100) additional to the source code zip/tar.gz. The first mentioned zip archive contains a snapshot of the repository, with the .git folder overall over 314 MB of data, without .git it's 47 MB. Is there a reason to not just ship the essential files in the package?

**Comment by idan** [comment]
Herp derp, you're right! Will update

**Comment by idan** [comment]
Fixed both the 1.1 and the 1.0 releases. Sorry about this, it was totally my messup.
