### ISSUE TITLE
`ss03` does not appear to enable `=>` arrow as documented

### ISSUE THREAD

**Issue by ian-h-chamberlain** [githubnext/monaspace#206]
Hi, thank you so much for the 1.100 release! It fixes a lot of quality-of-life issues and definitely seems like a big improvement overall.

In one case, however, I think a regression has been introduced — there doesn't appear to be any way to enable the `=>` arrow ligature without also enabling `≤` and `≥` ligatures (which I don't prefer to use). `ss02` apparently controls the `=>` arrow, but the README seems to indicate `ss03` should: https://github.com/githubnext/monaspace?tab=readme-ov-file#coding-ligatures

Examples:
<img width="680" alt="Screenshot 2024-05-04 at 14 09 49" src="https://github.com/githubnext/monaspace/assets/11131775/bc990131-11a9-49bf-909d-49e6cf5e7fb8">

<img width="739" alt="Screenshot 2024-05-04 at 14 09 59" src="https://github.com/githubnext/monaspace/assets/11131775/1223f5ac-421b-41b5-95e8-e65f0ec37ff7">

Is this a bug, or should the documentation be updated to reflect the behavior? Might there be any workaround (e.g. with `cv60` or something?)

**Comment by idan** [comment]
Investigating!

**Comment by ian-h-chamberlain** [comment]
Thanks! In the meantime discovered that `ss02` also seems to affect the spaceship operation `<=>`, so possibly all double-arrow ligatures would be affected, in case that's helpful for investigation.

**Comment by idan** [comment]
Should be fixed in e6f6278955d3c47a77c1bdbf442f60838667cb98! Thank you for the report 🥰
