### ISSUE TITLE
cv60 not working

### ISSUE THREAD

**Issue by chtenb** [githubnext/monaspace#207]
Tested on wezterm: 
![image](https://github.com/githubnext/monaspace/assets/1030961/32e21aef-8fa3-40f5-9980-19ebf1b2c170)

Regardless of whether ss02 is on or off, I don't get the back arrow for `<=`

**Comment by kenmcd** [comment]
Try `ss02`.
That turns `<=` into a ligature called `less_equal` (which looks similar to `≤`)
and then `cv60` turns that ligature into the arrow (`less_equal.alt`). 
So enable both `ss02` and `cv60`.

**Comment by chtenb** [comment]
That didn't work for me, like I said 😄

**Comment by kenmcd** [comment]
> That didn't work for me, like I said 😄

For some reason I had ss06 in my head.
Must have been doing too many things at once.
So...
What application are you using?
Does it support Character Variants? 
Some applications do not support them even though they do support Stylistic Sets.

**Comment by chtenb** [comment]
I didn't know that was a distinct feature. I'm using WezTerm (terminal): https://wezfurlong.org/wezterm/config/font-shaping.html#advanced-font-shaping-options

**Comment by idan** [comment]
Investigating!

**Comment by kenmcd** [comment]
@chtenb  Does it work if you only enable `ss02` and `cv60`?
There is mention in another issue that there may be some unwanted interactions between the stylistic sets.
I checked to see if other stylistic sets appeared to disable cv60, but that was in isolation, not within a run of text which may be affected by other features.
So try it with only `ss02` and `cv60` to see if WezTerm works.
That should answer the question if it supports cvNN.

**Comment by chtenb** [comment]
Maybe it's not a wezterm problem after all. I installed VSCode to test this font with a different application, and this is what I see:

![image](https://github.com/githubnext/monaspace/assets/1030961/5215fba9-1342-4a91-807b-4df9be6078ad)

**Comment by heathercran** [comment]
@chtenb I can't seem to replicate this issue in VS Code, even with your exact settings. Could you try pasting "" to ensure you have the latest version of the fonts installed? It should appear as "v1.100" in the latest Monaspace fonts. 

<img width="600" alt="Screen Shot 2024-05-07 at 3 06 44 PM" src="https://github.com/githubnext/monaspace/assets/166648890/c07753b6-52d5-431b-a6d2-3040d48ea2ed">

**Comment by chtenb** [comment]
That's a handy feature! And it revealed to me that the older version of monaspace was also still installed the newer version, and that the older version was chosen by the applications. I deleted all fonts starting with "mona" from my system and reinstalled again. Now it works!
