### ISSUE TITLE
Xenon letter l is  similar to 1 Is it possible to make l more curve ?

### ISSUE THREAD

**Issue by IvayloHrTonev** [githubnext/monaspace#209]
Hi, everyone

I really enjoy with Monaspace Fonts.
Especially Xenon ExtraBold, Really great job !
I just want to suggest to make l in Xenon more curve (similar to Krypton's l ) so it's easier to distinguish than number 1.

**Comment by idan** [comment]
Dupe of #62 

We're planning on doing something about this in the 1.2 milestone
