### ISSUE TITLE
Please Write README.md in Monaspace

### ISSUE THREAD

**Issue by VKrishna04** [githubnext/monaspace#214]
Please rewrite the `README.md` in Monaspace fonts and using texture healing as it can greatly help in easing the adoption of the fonts as everyone can see what and how this 5 variety font can be used in different situations especially in spaces such as outside the code editor but equally important areas.

**Comment by idan** [comment]
We can't force the github.com UI to render markdown files in Monaspace. Though I hope one day GitHub will use Monaspace for the website, for now you can point people at https://monaspace.githubnext.com.
