### ISSUE TITLE
Arrow function ligature not working

### ISSUE THREAD

**Issue by smlombardi** [githubnext/monaspace#217]
I'm using VSCode 1.89.1 on Windows 10 and the arrow function ligature does not show, for example
```
() => {
 console.log('Hello World');
}
```
I am using Monaspace Argon

```
  "editor.fontSize": 15,
  "editor.fontFamily": "'Monaspace Argon Light', monospace",
  "editor.fontLigatures": "'calt', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'liga'",
```

**Comment by nicolaerario** [comment]
I think has been moved to ss09 but it'not working actually. Not even in the site preview

![immagine](https://github.com/githubnext/monaspace/assets/37365465/4a17cff7-c5a6-4381-b0c2-7d286c58059a)

**Comment by heathercran** [comment]
@smlombardi were you able to see the arrow ligatures once you added `ss09` to your settings list?

**Comment by smlombardi** [comment]
Adding ss09 fixed it
