### ISSUE TITLE
Font Weight isn't fully adjustable

### ISSUE THREAD

**Issue by TinnyTerr** [githubnext/monaspace#220]
I had applied Monaspace Neon(using truetype) and was adjusting the font weight and found that it would only go to bold at 550 or above and everything underneath would default to the normal weight. I have a video attached of the weight being adjusted live.

https://github.com/githubnext/monaspace/assets/168141209/40b50341-336b-42bd-a217-e8f4ae47fbb9

**Comment by rileycran** [comment]
Can you please try this with another type family and see if you can get the result you're looking for? For instance, a default system monospace on your machine?

I think there may actually be an underlaying bug in VSCode itself here (?) as I can't get VS Code to display the 200 weight of Cascadia Code (the extra light font, which does exist) for example.

**Comment by TinnyTerr** [comment]
> Can you please try this with another type family and see if you can get the result you're looking for? For instance, a default system monospace on your machine?

> I can't get VS Code to display the 200 weight of Cascadia Code

Yeah, having the same issue with it. Seem its for vscode and variable fonts (instead of ones with like semibold, bold etc.). Thought since its one of the first fonts I thought about actually adjusting I guessed the issue was the font. My mistake.
