### ISSUE TITLE
Accented letters in Xcode

### ISSUE THREAD

**Issue by fran-6co** [githubnext/monaspace#221]
Hello.

I stopped using Monspace because I used it on Xcode but I got mad when I couldn't find the bug, and saw the minimal visualisation of accented letters when using them only with characters + ```´```. See in below picture how difficult is to see the accented with `´`:

![issue](https://github.com/githubnext/monaspace/assets/66537502/5ca562d4-1625-4b62-9ded-dea41968ab18)

I'm a standard user writing in Spanish. Not sure how to provide more useful information if so.

**Comment by rileycran** [comment]
Hello @fran-6co, one question for you: are you using the Static fonts or the Variable fonts?

When you specified a family of fonts to use, did you use 'Monaspace Argon' or 'Monaspace Argon Var'?

Xcode has some issues with variable fonts, but it should make good use of the static fonts.

**Comment by fran-6co** [comment]
I used variable fonts. Now I checked with otf and much better.

![image](https://github.com/githubnext/monaspace/assets/66537502/6876554f-9e9b-4edc-9c83-addb312c14eb)
