### ISSUE TITLE
Homebrew instructions are outdated

### ISSUE THREAD

**Issue by JPrevost** [githubnext/monaspace#225]
Running:

`brew tap homebrew/cask-fonts`

Results in:
 
`Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.`

I suspect homebrew changed how they are handling fonts, but I haven't had a chance to look closer into what the command should be updated to.

**Comment by injust** [comment]
https://github.com/Homebrew/homebrew-cask-fonts was deprecated and `font-monaspace` was migrated to `homebrew/cask`.

You can install using `brew install --cask font-monaspace`.

**Comment by JPrevost** [comment]
@injust thanks for taking the time to track the updated command.
