### ISSUE TITLE
Please add Comic Sans (serious)

### ISSUE THREAD

**Issue by tylerlaprade** [githubnext/monaspace#236]
Hi, this is not a troll post. I have been coding in [Comic Mono](https://github.com/dtinth/comic-mono-font) for a few months now. I really enjoy the legibility and the calming smooth curves. I am very excited about Monaspace's texture healing, but none of the five families meet my needs. I was hopeful that the handwritten Radon would suffice, but the slanted letters are jarring for me and make it hard to focus. I would love to see the innovative texture healing applied to a Comic Sans-esque font.

**Comment by heathercran** [comment]
Hi! Adding new style families to Monaspace is something that we'd love to do eventually, but it likely won't happen in the near future, as we're focusing on improving the performance of the existing fonts first.
