### ISSUE TITLE
Linux installation instructions and script

### ISSUE THREAD

**Issue by brunofin** [githubnext/monaspace#26]
Add a script and instruction for Linux installation similar to the ones provided for MacOS

**Comment by jfmcbrayer** [comment]
Installation instructions look correct. Do you know how or if it's possible to specify the ligature and texture healing options in a Pango font string?

**Comment by eliheuer** [comment]
The MacOS install script is very simple, can be ported to work with linux like just by replacing the font directory, like so:
```bash
#!/bin/bash

# remove all fonts from ~/. local/share/fonts that start with "Monaspace"
rm -rf ~/. local/share/fonts/Monaspace*

# copy all fonts from ./otf to ~/. local/share/fonts
cp ./fonts/otf/* ~/. local/share/fonts

# copy variable fonts from ./variable to ~/Library/Fonts
cp ./fonts/variable/* ~/. local/share/fonts

```
