### ISSUE TITLE
Variable fonts are horizontally stretched in terminals

### ISSUE THREAD

**Issue by injust** [githubnext/monaspace#267]
Version 1.101 installed via Homebrew

<details>
<summary>Ghostty Screenshots</summary>

<img width="940" alt="SCR-20241105-susj" src="https://github.com/user-attachments/assets/2c6e65b8-5db6-48ee-ad27-3ab3d14f2ba9">
<img width="940" alt="SCR-20241105-suqj" src="https://github.com/user-attachments/assets/2aea9de6-a369-4a33-a17a-3547fe41f1ee">

</details>

<details>
<summary>WezTerm Screenshots</summary>

<img width="940" alt="SCR-20241105-swnr" src="https://github.com/user-attachments/assets/2a2b51af-5cea-4dae-bdce-e20ba1a90a37">
<img width="940" alt="SCR-20241105-swlm" src="https://github.com/user-attachments/assets/99b12a68-bd87-4e1b-ac3d-e48f62795423">

</details>

**Comment by kenmcd** [comment]
What leads you to believe either of those applications support variable fonts?

**Comment by injust** [comment]
> What leads you to believe either of those applications support variable fonts?

I've tested both with other variable fonts (e.g. [Recursive](https://github.com/arrowtype/recursive)) to try and rule out terminal emulator bugs.
