### ISSUE TITLE
New version release anytime soon?

### ISSUE THREAD

**Issue by iwangbowen** [githubnext/monaspace#270]
I really love the fonts and would like to see new developments working on them😍😍😍

**Comment by clover256s** [comment]
毫无疑问monaspace是这个世界最美丽，最优雅，最完美的字体，它是如此的优雅，美丽。。。。

**Comment by iwangbowen** [comment]
> 毫无疑问monaspace是这个世界最美丽，最优雅，最完美的字体，它是如此的优雅，美丽。。。。

我也喜欢，我最喜欢的是可以将它的几种字体混用，同时能保持宽度一致

**Comment by heathercran** [comment]
Thank you so much! A new version will be released very soon 😄

**Comment by iwangbowen** [comment]
> Thank you so much! A new version will be released very soon 😄

Appreciate it
