### ISSUE TITLE
Argon Var SemiWide not working for VSCode

### ISSUE THREAD

**Issue by simplerethink** [githubnext/monaspace#271]
Does anyone know how to activate `"fullname" : "Monaspace Argon Var Regular SemiWide Regular"` in VScode on MacOS?

Seems I can only get `"editor.fontFamily": "'Monaspace Argon Var'"` to work but not the variant `SemiWide Regular`.

**Comment by heathercran** [comment]
This seems to be a bug with some editors, where they won't read a font style name as part of the font family name: [https://stackoverflow.com/questions/36085443/how-to-specify-bold-font-in-vs-code-editor](url) 

If you're on a Mac, you can work around this by removing the spaces and adding a hyphen between the family name and style name: `"editor.fontFamily": "'MonaspaceArgonVar-SemiWideRegular'`. (You also have an extra "Regular" in your snippet above, so if you aren't on a Mac, that might solve your issue!)

With the variable fonts, you can also define the weight and width separately using `"editor.fontVariations": "'wght' 400, 'wdth' 112"`. This will give you much finer control of your font settings.
