### ISSUE TITLE
Add ligature for >>=

### ISSUE THREAD

**Issue by ambertide** [githubnext/monaspace#31]
`>>=` is a popular operator used in the Haskell and Haskell inspired programming languages, although not as popular as other languages they still occupy a space in functional programming

Right now monaspace turns `>=` to a ligature, and `>>=` looks like `>≥` which looks ugly in my opinion

Maybe a future version of the font could have the `>>=` ligature?

**Comment by shurizzle** [comment]
Spaceship operator (<=>) looks ugly too for the same reason.

**Comment by spenserblack** [comment]
Besides Haskell, `>>=` and `<<=` are valid bitwise operations in several languages (JavaScript, Python, Ruby).

**Comment by ambertide** [comment]
Oh yes, it is probably valid in a lot of languages now that I think about it like that

**Comment by konn** [comment]
It would be nice to have flipped version `=<<` and brackets `[|` and `|]` too.

**Comment by idan** [comment]
Fixed in ca8015b
