### ISSUE TITLE
Fontfamily not activating in VSCode? 

### ISSUE THREAD

**Issue by PsySolix** [githubnext/monaspace#32]
So I first followed the readme, for MACOSX & ran the bash file. 
Then verified if I have all the fonts in Font Book -> they are there. 

## Using the following options in VSCODE: 
`"editor.fontLigatures": true,`
`"editor.fontFamily": "Monaspace, Arial, serif",` // for testing

> Also tried with the Monaspace _____

## Result
Seeing Arial being used in the editor... Is there something that I'm missing? 

Thanks in advance!

**Comment by PsySolix** [comment]
## Solution: 

Okay so for people having the same "oopsie" moment as me.. the _____ is the name of the variant of the package. So for VSCode you need: 

```
"editor.fontFamily": "'Monaspace Neon', serif", (or Argon or ...)
```

**Comment by roel4ez** [comment]
FWIW, for me it only works by specifying the full Font name, e.g. `Monaspace Neon Var`
![image](https://github.com/githubnext/monaspace/assets/1822123/c13ab90f-efdf-4bdb-980f-da409d181873)

```json
"editor.fontFamily": "'Monaspace Neon Var', monospace"
```

**Comment by balupton** [comment]
Yeah, I was thinking I would specify just `Monaspace` and then it would mix and match accordingly. Seems that is not the case: https://github.com/githubnext/monaspace/issues/6

**Comment by athompson-merlin** [comment]
See one identified possible root cause at #111.

**Comment by idan** [comment]
Whoops, GH auto closed this when I merged #125 

We'll produce a new build soon and check that this (and related issues) are solved.

**Comment by akselerando** [comment]
Just wanted to add (in case someone else was stuck with the same problem as me), that the fonts only appeared in vscode for me after *closing* and *reopening* the window. Just hitting Ctlr+Shift+P and `Developer: reopen window` was not enough

**Comment by sujeewasandeepa** [comment]
Do you guys know how to use different variants like 'medium' on VS Code. Using it like this 
`Monaspace Neon Var Medium` doesn't work.

**Comment by yvvt0379** [comment]
Try adding this line to settings.json:
```json
"editor.fontWeight": "medium",
```

**Comment by heathercran** [comment]
I'd recommend using the static Monaspace fonts in VS Code, as it doesn't fully support variable fonts yet. That should allow you to set the font weight as normal.
