### ISSUE TITLE
Feature: Add Homebrew Installation Method

### ISSUE THREAD

**Issue by validatedev** [githubnext/monaspace#38]
As stated.

**Comment by powellb** [comment]
That is a homebrew issue, but:

`homebrew update && homebrew install font-monaspace`

works fine.

**Comment by krehel** [comment]
Homebrew availability was completed per https://github.com/Homebrew/homebrew-cask-fonts/pull/8651

Instructions update appear to be pending at https://github.com/githubnext/monaspace/pull/33

**Comment by validatedev** [comment]
Yay! Thank you for the info
