### ISSUE TITLE
Don't include docs images in the package download

### ISSUE THREAD

**Issue by krzysztofjeziorny** [githubnext/monaspace#41]
First of all, thank you for a beautiful font family!

One small request though: Downloading 97MB of images together with fonts is rather unnecessary? I think it's enough to have the documentation examples online - no need to include it in the download zip.

**Comment by sabi0** [comment]
The 7 (ridiculously large) GIFs occupy 75% of the distribution package.
Once removed the .zip archive size drops from 117 MB to just 25 MB.

**Comment by idan** [comment]
My bad! Fixed in both the 1.0 and 1.1 releases.
