### ISSUE TITLE
Equal and colon characters should be vertically aligned

### ISSUE THREAD

**Issue by galdor** [githubnext/monaspace#45]
In 1.0, the equal and colon characters are not vertically aligned which is unsettling for the `:=` sequence used for example in Go.

**Comment by ian-h-chamberlain** [comment]
I believe the `calt` ligature aligns vertically like you expect, see https://github.com/githubnext/monaspace#coding-ligatures

**Comment by heathercran** [comment]
In the latest font update, `ss07` will align these characters vertically.
