### ISSUE TITLE
Add a ligature for jsdoc comment start string: “/**”

### ISSUE THREAD

**Issue by kizu** [githubnext/monaspace#50]
See https://jsdoc.app/about-getting-started over how JSDoc comments are used. One common form is a one-line like

```js
/** This is a description of the foo function. */
```

Which, when using the `/*` ligature is not rendering in a very pretty way:

<img width="516" alt="A screenshot of the above code as rendered with monaspace Neon" src="https://github.com/githubnext/monaspace/assets/177485/d5b62738-7eb7-48d3-8fd4-901ba6699daf">

I think it would be nice to lower the second `*` in a `/**` sequence.

**Comment by nizur** [comment]
#2

**Comment by kizu** [comment]
Oops, did not notice that one, would close as a duplicate, thanks for pointing it out!
