### ISSUE TITLE
U+2123 VERSICLE should not be a font version number indicator

### ISSUE THREAD

**Issue by dscorbett** [githubnext/monaspace#51]
The glyph for U+2123 VERSICLE is a font version number indicator, currently “v1.000”. This violates the Unicode Standard’s conformance requirement about character identity. The glyph should instead be mapped to a private use character.

**Comment by idan** [comment]
Derp, we intended to move it to U+E123 but forgot to in the pre-launch crush. We'll fix it in the next release!

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
