### ISSUE TITLE
Hyphen, minus sign and en dash are indistinguishable

### ISSUE THREAD

**Issue by nuntius35** [githubnext/monaspace#55]
I would expect that the font provides a clear distinction between - (U+002D HYPHEN-MINUS), − (U+2212 MINUS SIGN), – (U+2013 EN DASH), and — (U+2014 EM DASH). The screenshot shows that the first three of these glyphs look identical. 

![image](https://github.com/githubnext/monaspace/assets/11093229/8509f22f-419f-492d-bfe9-062d28404587)

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
