### ISSUE TITLE
Baseline not consistent for all characters

### ISSUE THREAD

**Issue by prplecake** [githubnext/monaspace#57]
The baseline for some characters is much higher than the rest of the line.

In Sublime Merge on Windows using Monaspace Argon: (note the "X" is higher than "ML")
![image](https://github.com/githubnext/monaspace/assets/83595468/3b929c0f-77f1-4ebc-9e4c-124f325ade61)

**Comment by Finii** [comment]
This is really a point problem, the basline of `X` sits on vertical coordinate 2, and `M` and `L` as expected on 0:

![image](https://github.com/githubnext/monaspace/assets/16012374/5640affb-d3e7-4164-9df6-3a85bc456377)

**Comment by Finii** [comment]
![image](https://github.com/githubnext/monaspace/assets/16012374/88cd1b6e-dd44-4f58-9ed5-2c13a7352740)
_Path of X_

![image](https://github.com/githubnext/monaspace/assets/16012374/de56a085-114c-4bcb-a5f9-0afa51141f1b)
_Path of M_

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
