### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by alckordev** [githubnext/monaspace#58]
Ligatures dont work

**Comment by kcoderhtml** [comment]
Have you followed the instructions to enable them in the settings.json of VS Code?

**Comment by K4R7IK** [comment]
```
 "editor.fontFamily": "'Monaspace Neon' , Consolas, 'Courier New', monospace",
 "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'calt', 'dlig'",
```

@alckordev add the following in your `settings.json`

**Comment by alckordev** [comment]
> ```
> 
>  "editor.fontFamily": "'Monaspace Neon' , Consolas, 'Courier New', monospace",
> 
>  "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'calt', 'dlig'",
> 
> ```
> 
> 
> 
> @alckordev add the following in your `settings.json`

Thanks 👍🏻
