### ISSUE TITLE
Kerning issue with double forward slash ( `https://github...` )

### ISSUE THREAD

**Issue by cpdean** [githubnext/monaspace#60]
In the default Terminal.app on macOS, the kerning immediately following two forward slash characters causes the next character to share the same space in the grid.  For example, `https://github...` renders as:

<img width="362" alt="image" src="https://github.com/githubnext/monaspace/assets/160099/f2233ad6-ca51-4540-bf92-7c7ecc927680">

Another example:

```
**hey
//hey
```

<img width="230" alt="image" src="https://github.com/githubnext/monaspace/assets/160099/f97802b1-62f0-4302-abbe-cf354f511496">

Besides just the rendering issue, the kerning is severe enough that the terminal's cursor will appear offset for every character after the double forward slash.  In the following two screenshots, the cursor is highlighting the letter `y` of `hey`

<img width="192" alt="image" src="https://github.com/githubnext/monaspace/assets/160099/447c93ff-21d5-4de2-ab46-baddd7ebb3b0">
<img width="220" alt="image" src="https://github.com/githubnext/monaspace/assets/160099/f3209bf7-46c8-4bfa-8dc0-0518123edee5">

**Comment by 33b5e5** [comment]
I can reproduce this on macOS Sonoma 14.1.1, using the default Terminal.

The overlapped text only appears with the variable fonts. For example:

Monaspace Neon Regular, size 14: ok
Monaspace Neon Var, size 14: overlapped

The pattern holds across the other 4 fonts. All the variable versions are bugged for `//`.

The behavior is the same from a zsh prompt, in vi, or using cat.

**Comment by gustafe** [comment]
Same sort of behavior can be seen by inputting 2 or more dots (periods) instead of slashes.

**Comment by jamesez** [comment]
There's a workaround, flip to the non-"Var" version, which - for me - showed up in All Fonts and not under Fixed Width: https://github.com/githubnext/monaspace/issues/79#issuecomment-1811569036

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
