### ISSUE TITLE
Linux Install Script Issues

### ISSUE THREAD

**Issue by abeljim** [githubnext/monaspace#63]
Currently the Linux install script needs to be run from outside the util folder unlike the readme.
The install also fails of the ~/.local/share/fonts does not exist.

**Comment by idan** [comment]
Fixed in 702a2568628b16fa3ddef4aae46e3e3e8c6b052a, 52cc7507c7f4b600925dc9f6c5e2dd1cfb575e11, 8847e6c809aae8afac2ea9e137850fe870862421
