### ISSUE TITLE
ligature 8< should become ✀ U+2700

### ISSUE THREAD

**Issue by kapouer** [githubnext/monaspace#72]
This is a feature request.

Thanks !

**Comment by yvvt0379** [comment]
No, I don't think these symbols should be ligaturized. Certainly, we don't want `if (8<someExpression)` look wrong.

**Comment by kapouer** [comment]
-8<- ? :)

**Comment by ToxicFrog** [comment]
This sounds like it's more of something to do with your XCompose; set it up so that `compose 8 <` emits ✀

**Comment by idan** [comment]
This is cute, but it's not very common, and best left to other tools like xcompose/wincompose.
