### ISSUE TITLE
Some odd clumping patterns with repeated symbols

### ISSUE THREAD

**Issue by jneen** [githubnext/monaspace#75]
See this htop output, rendered in Neon Regular:

<img width="738" alt="image" src="https://github.com/githubnext/monaspace/assets/225017/14c3537d-53d3-4d60-8787-934b39a3c70f">

Compare to e.g. Menlo:

<img width="738" alt="image" src="https://github.com/githubnext/monaspace/assets/225017/ab6e720d-0d1e-407e-adb7-022566c96c2f">

**Comment by Logo121** [comment]
Isn't this due to the `||` ligature in the `calt` ligature set?

`|` doesn't seem to have texture healing alternates.

**Comment by jneen** [comment]
Probably! Updated the title to reflect

**Comment by chtenb** [comment]
Here is some similar behavior with === ligatures

![image](https://github.com/githubnext/monaspace/assets/1030961/486242cd-4aaf-4b31-8be8-519364f0862b)

Other fonts with ligature support handle this more gracefully

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
