### ISSUE TITLE
GitHub README references editor.fontLigatures value "liga" while project web page makes no mention of that value

### ISSUE THREAD

**Issue by DavidAnson** [githubnext/monaspace#77]
See:
- <https://github.com/githubnext/monaspace#visual-studio-code> which says `You must start the setting with 'calt', 'liga', 'dlig'!`
- <https://monaspace.githubnext.com> section "Code ligatures" which lists only `"editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'calt', 'dlig'",`

Aside: It's also possibly confusing that the first reference says one must **start** with those settings and the second reference puts them at the **end**.

**Comment by Zeta611** [comment]
I've found out that only the latter properly enables `dlig` ligatures like `|>` (I guess?). The `"'calt', 'liga', 'dlig', 'ss01', ..."` does not work.

**Comment by nickmccurdy** [comment]
It seems like me like excluding `'calt'` and `'liga'` does nothing in VSCode https://github.com/githubnext/monaspace/issues/118#issuecomment-1815927269

**Comment by nickmccurdy** [comment]
This appears to be a [VSCode bug](https://github.com/microsoft/vscode/issues/198517). However the documentation should still be consistent.

**Comment by idan** [comment]
Hi there! In v1.1, `liga` takes on a specific meaning, and `dlig` has been removed. See the [coding ligatures section in the readme](https://github.com/githubnext/monaspace?tab=readme-ov-file#coding-ligatures).
