### ISSUE TITLE
[bug] ligature of character "/" triggers overlap with the next character

### ISSUE THREAD

**Issue by cdluminate** [githubnext/monaspace#79]
![image](https://github.com/githubnext/monaspace/assets/5723047/3c81b2ef-8577-4cf7-9023-475eee4dc33a)

Mac OS terminal.
Font variant is Argon Var Regular Light 12.

I think this is triggered by the ligature feature, because a single slash does not trigger the character overlap.

**Comment by Logo121** [comment]
#60

**Comment by 33b5e5** [comment]
I can reproduce this on macOS Sonoma 14.1.1, using the default Terminal.

The overlapped text only appears with the variable fonts. For example:

Monaspace Neon Regular, size 14: ok
Monaspace Neon Var, size 14: overlapped

The pattern holds across the other 4 fonts. The variable versions are bugged for `//`.

The behavior is the same from a zsh prompt, in vi, or using cat.

**Comment by garthk** [comment]
Confirmed on Ventura, Terminal.app.  Workaround: choose "Monaspace Neon", not "Monaspace Neon Var". Suspicion for further bug hunting: why are the Var versions only displayed in the "Fixed Width" collection?

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
