### ISSUE TITLE
Healed double "m" looks strange 

### ISSUE THREAD

**Issue by markwhitfeld** [githubnext/monaspace#81]
When a double "m" is positioned next to a narrow and wide letter on either side, it looks strange. Could there be any solutions for this?

![Screenshot_20231112_110004_Chrome.jpg](https://github.com/githubnext/monaspace/assets/1948265/18c2ecc1-3fa5-4f34-a459-41e90834e41b)

**Comment by daniel-l** [comment]
See #74

**Comment by markwhitfeld** [comment]
This is a duplicate of #42 and #74. Closing in favour of those.

**Comment by markwhitfeld** [comment]
Duplicate of #42 
Duplicate of #74

**Comment by markwhitfeld** [comment]
Duplicate of #42

**Comment by markwhitfeld** [comment]
I have no idea how to get github to close this as a duplicate. I don't think I have the right permissions.
