### ISSUE TITLE
Maybe mention Andreas Larsen's monoid as a similar approach to texture healing?

### ISSUE THREAD

**Issue by JobLeonard** [githubnext/monaspace#85]
Andreas Larsen's monoid, an open source font from 2015, uses a similar approach to texture healing. The big difference visually speaking is that it does not resize glyphs, it only repositions them:

https://medium.com/larsenwork-andreas-larsen/class-based-contextual-positioning-in-monospaced-fonts-cb6b8b9ffe6f

Still, the problem it is trying to solve is exactly the same, and contextually adjusting kerning is very similar to texture healing.

I don't want to suggest that you took inspiration from his font, but I think it's nice when articles introducing ideas acknowledge other similar works. In a way it also lends some credence to the idea, right? *"Look, it's not just us! Someone else was annoyed enough with the exact same problem that he came up with a very similar solution!"*

**Comment by idan** [comment]
Hello!

Hey that's cool, we've never seen this before. Ultimately, as you say, Texture Healing is a different approach to a problem that has existed in monospaced faces since forever. If we decide to expand our docs to include references to others' fonts, we'll include a reference to Monoid.
