### ISSUE TITLE
 fonts are not recognized in IntelliJ IDEA on windows 11

### ISSUE THREAD

**Issue by 1xiaofeng1** [githubnext/monaspace#94]
Hello, fonts are not recognized in IntelliJ IDEA on windows 11, no matter if installed otf or variable.
windows 11 23H2  22631.2506

**Comment by iamntz** [comment]
@1xiaofeng1 see here: https://github.com/githubnext/monaspace/issues/20

**Comment by aardvark** [comment]
> @1xiaofeng1 see here: #20

Please note that #20 is fixed by workaround, font installation should not require "Install for all users" to be visible in IDE or other program.

**Comment by 1xiaofeng1** [comment]
> @1xiaofeng1 see here: #20

It's okay, thank you very much

**Comment by 1xiaofeng1** [comment]
> > @1xiaofeng1 see here: #20
> 
> Please note that #20 is fixed by workaround, font installation should not require "Install for all users" to be visible in IDE or other program.

It's okay, thank you very much

**Comment by idan** [comment]
Whoops, GH auto closed this when I merged #125 

We'll produce a new build soon and check that this (and related issues) are solved.
