### ISSUE TITLE
The font Settings do not take effect

### ISSUE THREAD

**Issue by KiligFei** [githubnext/monaspace#95]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: windows

Steps to Reproduce:

1. Download github（https://github.com/githubnext/monaspace/releases/tag/v1.000） Open source fonts
2. Select Install for all users
3. Set the vscode font

**Comment by Krymancer** [comment]
I'm having the same issue

**Comment by wsow4** [comment]
> I'm having the same issue, what did you do to have this problem solved?

Just restart (not reload) VS Code after installing any new font. Then set `"'Monaspace Neon Var', monospace"` as a `editor.fontFamily` value.
