### ISSUE TITLE
Texture healing makes some strings look out of place

### ISSUE THREAD

**Issue by kacperfronc** [githubnext/monaspace#96]
There are some strings that look ridiculously out of place with Texture Healing.

For example:
![IMG_0562](https://github.com/githubnext/monaspace/assets/30493915/7dd9be33-f8cc-4fd8-96c5-35828f7fac97)

While in theory it works as intended, I guess, this is such a stark difference that I had to make  a few double checks if that’s for sure same ‘0’ character

I’m using PyCharm 2023.2.4
Font setting is:
Monaspace Neon
Size - 15.0, Line height - 1.5, ligatures enabled

**Comment by auderson** [comment]
Hi, may I ask how do you set the fonts in pycharm? I'm using win11 and pycharm can't see the fonts I installed.

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0
